server:
  port: 9090
spring:
  application:
    name: one-to-one-bidirectional
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/subhakar-code?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root